### ISSUE TITLE
Generate image from results

### ISSUE THREAD

**Issue by Pitenager** [jobtalle/CubicNoise#3]
Hi dude, 

I have a question about the use of CubicNoise: how did you get the images from the code?
I am doing it from Python and what I have done is to declare a 2D array of 128x128 filling each position with a value obtained from the "sample" function, but now I do not know how to convert that matrix into an image, any suggestions?

Thank you !

**Comment by jobtalle** [comment]
Check this out: https://dev.to/petercour/generate-images-with-python-pil-302k
