### ISSUE TITLE
Demo isn't consistent?

### ISSUE THREAD

**Issue by Zireael07** [jobtalle/CubicNoise#6]
Clicking generate gives me a different terrain about 50% of the time...
![Screenshot_20210402_120922](https://user-images.githubusercontent.com/4525388/113406824-74502700-93ac-11eb-9cb4-a98c889b91c3.jpg)

**Comment by jobtalle** [comment]
Found the issue: the noise was offset randomly when generating. The noise was seeded, but the offset changes every time. I've fixed that and will upload it to the blog soon, thanks!
